api_version = "2025-07"

[[extensions]]
name = "Sellence Cart Transform"
handle = "sellence-cart-transform"
type = "function"
uid = "6c6a19dc-7a54-85aa-84c5-2f327a014a734b69b802"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
